#pragma once

#include <QString>
#include <QByteArray>

/**
 * @file ExportCrypto.h
 * @brief Lightweight symmetric encryption for quiz export files.
 *
 * Goal: make answer data in exported JSON/CSV files unreadable without
 * the application.  Students who open the file in a text editor or import
 * it into another tool must not be able to read the correct answers.
 *
 * Algorithm: XOR-stream cipher with a SHA-256-derived key.
 *   1. key  = SHA-256( APP_SECRET + salt )   [32 bytes]
 *   2. keystream is generated by repeatedly hashing key blocks:
 *        block_0 = SHA-256(key || counter_0)
 *        block_1 = SHA-256(key || counter_1)  …
 *   3. plaintext XOR keystream = ciphertext
 *   4. Output: Base64( salt[16 bytes] || ciphertext )
 *
 * Security level: appropriate for an offline educational tool.
 * It is NOT suitable for protecting secrets against a determined adversary
 * with access to the binary (the APP_SECRET is in the binary).
 * The goal is casual-user deterrence, not cryptographic security.
 *
 * For true security, replace with AES-256-CBC via OpenSSL or Qt Network's
 * QSslConfiguration (requires linking against openssl).
 */
class ExportCrypto
{
public:
    ExportCrypto() = delete;

    /**
     * @brief Encrypt plaintext and return a Base64-encoded string.
     * @param plaintext  UTF-8 string to encrypt.
     * @return  Base64( salt || ciphertext ), never empty on success.
     */
    static QString encrypt(const QString& plaintext);

    /**
     * @brief Decrypt a Base64-encoded ciphertext produced by encrypt().
     * @param base64Cipher  Value produced by encrypt().
     * @param ok            Set to false if decryption fails (bad format/key).
     * @return  Original plaintext, or empty string on failure.
     */
    static QString decrypt(const QString& base64Cipher, bool* ok = nullptr);

    /**
     * @brief Returns true if the string looks like an encrypted blob
     * (i.e. valid Base64 with the expected minimum length).
     * Quick pre-check before calling decrypt().
     */
    static bool looksEncrypted(const QString& value);

private:
    /// 16 random bytes prepended to ciphertext (changes every encrypt call).
    static QByteArray generateSalt();

    /// Derive a 32-byte key from the application secret and a salt.
    static QByteArray deriveKey(const QByteArray& salt);

    /// XOR-stream cipher (encrypt and decrypt are the same operation).
    static QByteArray xorStream(const QByteArray& data, const QByteArray& key);

    /// Application-specific secret mixed into every key derivation.
    /// Changing this value invalidates all previously exported files.
    static constexpr const char* APP_SECRET =
        "CppAtlas::ExportCrypto::v1::8f3a2e1b9c7d4f0e";
};
